name: ci

on:
  push:
    tags:
      - "v*.*.*.beta"
      - "v*.*.*.beta*"

  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: echo
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF}" >> $GITHUB_ENV
          echo ${{ toJson(github.event) }}
          echo ${{ env.RELEASE_VERSION }}
