name: continuous integration

on:
  push:
    branches:
      - v*.*.*_dev

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          go test ./...
