name: continuous integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.2]

    #services:
    #mongo:
    #image: mongo:latest
    #ports:
    #- 27017:27017

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run Test
        run: |
          docker run --rm -w /app -v ${PWD}:/app golang go test ./...
      #- name: Build test environment
      #run: |
      #docker run --rm -w /app -v ${PWD}:/app golang go test ./...
      #cd /app
      #go test ./...
    #steps:
    #- name: Install Go
    #uses: actions/setup-go@v2
    #with:
    #go-version: ${{ matrix.go-version }}
    #- name: Checkout code
    #uses: actions/checkout@v2
    #- name: Test
    #run: |
    #go test ./...
