name: ci

on:
  push:
    tags:
      - "v*.*.*.beta"
      - "v*.*.*.beta*"

  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: echo
        run: |
          echo ${{ toJson(github) }}
          echo ${{ github.event.repository.git_commits_url }}
